name: Deploy API

on:
workflow_dispatch:

jobs:
deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Build JAR
    run: |
      ./mvnw clean package

  - name: Deploy to EC2
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        pkill java || true
        rm -f app.jar
        mv target/*.jar app.jar
        nohup java -jar app.jar > app.log 2>&1 &
