name: Deploy API

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 26
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew clean build

      - name: Find JAR file
        run: ls build/libs

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill java || true

            echo "Removendo jar antigo..."
            rm -f app.jar

            echo "Listando arquivos recebidos..."
            ls -la

            echo "Renomeando jar..."
            mv *.jar app.jar

            echo "Subindo aplicação..."
            nohup java -jar app.jar > app.log 2>&1 &

            echo "Processos Java ativos:"
            ps aux | grep java | grep -v grep